### ISSUE TITLE
Git version tag

### ISSUE THREAD

**Issue by rgieseke** [konstantinstadler/country_converter#10]
>  Version: Does the release version given match the GitHub release (v0.4)?

Could you tag the version published on PyPI in Git as well? This is also helpful for the Zenodo archiving.

(https://github.com/openjournals/joss-reviews/issues/332)

**Comment by konstantinstadler** [comment]
The version uploaded an PyPI (0.4) is already tagged, I added a badge in the readme pointing to the current version available at PyPI.

**Comment by konstantinstadler** [comment]
I also added a zenodo badge for the previous major version (0.4) - a new release will follow after the JOSS review.
