### ISSUE TITLE
"Hong Kong (China)" in IEA data is not found

### ISSUE THREAD

**Issue by Kajwan** [konstantinstadler/country_converter#106]
For some reason the country converter can seem to find "Hong Kong (China)" in the data when trying to convert IEA country name. 
Not sure why, as the "Hong Kong (China)" clearly is in the data table. 

So `coco.convert("Hong Kong (China)", src="IEA", to="EXIO3")` returns `not found`.
While `cc.data.IEA.loc[cc.data.IEA.values == "Hong Kong (China)"]` returns
```
100    Hong Kong (China)
Name: IEA, dtype: object
```

**Comment by Kajwan** [comment]
Right, so the issue is in 
```
    result_list = [
        etr[0]
        for etr in self.data[
            _match_col.str.contains(
                "^" + spec_name + "$", flags=re.IGNORECASE, na=False
            )
        ][to].values
```
in `pd.Series.str.contains()`, `regex=True` by default. However, this messes the search, as the brackets "( )" makes it think it is a subexpression. However, we can't set the regex to False without removing the "^" and "$" strings. 
I see two solutions: 
1. We first have it run a `regex=False` version of the command above. If that is unsuccessful, we run a `regex=True` version.
2. We have the code replace "(" and ")" with "\(" and "\)" somewhere before running the matching. Potentially in the `_separate_exclude_cases function`. 

The later is probably the cleaner version.

**Comment by konstantinstadler** [comment]
Nah, I think we will just wrap the spec_name in [re.escape ](http://docs.python.org/library/re.html#re.escape) - you wanna give it a try and send a pull request?

**Comment by Kajwan** [comment]
That was a better suggestion. I have made the pull request.

**Comment by konstantinstadler** [comment]
closed via re.escape
