### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by rgieseke** [konstantinstadler/country_converter#11]
Could you maybe add some instructions on how to run the tests? This would be helpful for people not familiar with py.test.

I used (after cloning the repo):

```
python3 -m venv venv
./venv/bin/pip install -e .
./venv/bin/pip install pytest
./venv/bin/pytest --verbose
```

(https://github.com/openjournals/joss-reviews/issues/332)

**Comment by konstantinstadler** [comment]
I added a section
"Running and extending the tests"
in CONTRIBUTING.rst and link to this description when I mention pytest in the README.rst
