### ISSUE TITLE
Macedonia Official Name out of Date

### ISSUE THREAD

**Issue by nschimmoller** [konstantinstadler/country_converter#110]
Per the [Prespa agreement](https://en.wikipedia.org/wiki/Prespa_agreement) signed by Macedonia and Greece in June 2018 the new name for the country should be North Macedonia and it's official name Republic of North Macedonia. 

I'd make a PR to correct this in the country table, however I would imagine this impacts the compatibility with the Locales documents. Let me know if that's incorrect!

**Comment by nschimmoller** [comment]
Update, it seems as though no LOCALES_DIR folder that has an iso3166.mo file in it has a translation specified for Macedonia or North Macedonia. In all cases the gettext call just returns the original inputted value. 

Happy to share my code (probably bad) if helpful.

**Comment by nschimmoller** [comment]
While we're on the topic seems like something similar is develop for Turkey, soon to be Türkiye.

**Comment by konstantinstadler** [comment]
These updates will be in the new 0.7.5 release

**Comment by nschimmoller** [comment]
@konstantinstadler thanks for following up on this. Apologies for the confusion I'm sure my comment on June 3rd created. I'm 99% I got confused what I was using from pycountry vs country_converter
