### ISSUE TITLE
Update India regex to avoid matching Bassas Da India

### ISSUE THREAD

**Issue by mcarans** [konstantinstadler/country_converter#111]
I would like to suggest updating the India regex to avoid matching "Bassas Da India", a French atoll that is part of the French Southern and Antarctic Lands.

**Comment by mcarans** [comment]
After some experimenting, I think this will work:
`^(?!\D*(?:bassas))\D*india(?!.*ocea)(?!na)`

**Comment by konstantinstadler** [comment]
Thanks a lot! will be added in the new release in the next days
