### ISSUE TITLE
Korea regex fails

### ISSUE THREAD

**Issue by rpelicaen** [konstantinstadler/country_converter#114]
I run the code
```python
locations = [location.text for location in root.iter('location')]
cc = coco.CountryConverter()
short_countries = cc.convert(names = locations, to = 'name_short')
````
which returns
```python
KeimyungUniversity, Daegu, Jung-gu, Korea, Republic of not found in regex
Severance hospital, Seoul, Korea, Republic of not found in regex
```

**Comment by konstantinstadler** [comment]
It matches Korea, Republic
you have a lot of other stuff in the string - perhaps clean that first?
Or you can try to play with the regex of South Korea in the data file - it is very tricky b/c of the north/south korea similarities. But I am very happy to accept pull requests for improvments
