### ISSUE TITLE
Case issue in UN M.49 region "South-eastern Asia"

### ISSUE THREAD

**Issue by alanorth** [konstantinstadler/country_converter#115]
Apologies for the minor nitpick. I use country_converter in some projects and always have to deal with the case of the UN M.49 region "South-eastern Asia" manually because country_converter has it as "South-Eastern Asia" with a capital E. I double checked the [UNSD website](https://unstats.un.org/unsd/methodology/m49/) and their [CSV data export](https://unstats.un.org/unsd/methodology/m49/overview/) and they use a lowercase "e".

Thank you!

**Comment by konstantinstadler** [comment]
Not nitpicking. Such feedback helps a lot. I will fix that in the next release
