### ISSUE TITLE
Kosovo XKX not KSV

### ISSUE THREAD

**Issue by mcarans** [konstantinstadler/country_converter#29]
Thanks for your project!

I think Kosovo's 3 letter code should be XKX not KSV.

**Comment by konstantinstadler** [comment]
The iso3 code for Kosovo seems not to be fixed yet (its not included in the UN codes AFAK). Just found the info that the Worldbank changed its code for Kosovo from KSV to XKX.
Do you have any "official" data source to back XKX up?

**Comment by mcarans** [comment]
Yes I found XKX in the World Bank too and various websites like https://countrycode.org/kosovo but not something more official than the WB. Where did you get KSV as I haven't managed to find the source for that in my searching?

**Comment by konstantinstadler** [comment]
Probably I had it from the worldbank before they changed or the Eora classification. Do you have a link to the worldbank country list with iso3 codes?

**Comment by konstantinstadler** [comment]
Fixed in 0.6.4
