### ISSUE TITLE
Remove or mark obsolete Zanzibar, Tanganjika and Netherlands Antilles

### ISSUE THREAD

**Issue by mcarans** [konstantinstadler/country_converter#30]
"In April 1964, the republic (Zanzibar) merged with mainland Tanganyika. This United Republic of Tanganyika and Zanzibar was soon renamed, blending the two names, as the United Republic of Tanzania,"
https://en.wikipedia.org/wiki/Zanzibar

**Comment by mcarans** [comment]
"The acts of parliament integrating the "BES" islands (Bonaire, Sint Eustatius and Saba) into the Netherlands were given royal assent on 17 May 2010. After ratification by the Netherlands (6 July), the Netherlands Antilles (20 August), and Aruba (4 September), the Kingdom act amending the Charter for the Kingdom of the Netherlands with regard to the dissolution of the Netherlands Antilles was signed by the three countries in the closing Round Table Conference on 9 September 2010 in The Hague."
https://en.wikipedia.org/wiki/Netherlands_Antilles#Dissolution

**Comment by konstantinstadler** [comment]
Yes, we have several cases of country names and classifications no longer in use.
However, as this package is used for processing past economic data we keep these in there. The purpose is not to provide an up-to-date list of current and/or official countries. Having said that, I fully understand the problem and we had such an issue before. As a consequence, country converter now includes a parameter to only consider official UN members - see https://github.com/konstantinstadler/country_converter#classification-schemes
