### ISSUE TITLE
Add third option to show all countries but not obsolete

### ISSUE THREAD

**Issue by mcarans** [konstantinstadler/country_converter#32]
It's great you have UN recognised as an option, but I think you need one more which is all countries except those that have become obsolete. One reason is that if you list countries in a region using the all option eg. Europe, you could get duplicates eg. getting Channel Islands as well as Jersey and Guernsey. UN recognised can be too strict eg. excluding Taiwan.

**Comment by konstantinstadler** [comment]
Yes, but what would that list be? There is no "official" list of countries in the world. The closest I can find was the UN. Everything beyond that is subjective - e.g. even the the Taiwan case, as it is not recognised as an official country by several others...

**Comment by mcarans** [comment]
I understand your point. How about this then: label locations which have been either included officially in another location eg. Zanzibar or which have been split into multiple recognised locations eg. Jersey, Guernsey?

**Comment by konstantinstadler** [comment]
Sounds ok. If you want you can implement that and issue an merge request.

**Comment by mcarans** [comment]
Ok I have made a pull request: https://github.com/konstantinstadler/country_converter/pull/33

**Comment by konstantinstadler** [comment]
Many thanks for your help!
All your changes are included in version 0.6.5 - already available on pypi and anaconda.
