### ISSUE TITLE
Swaziland is now Eswatini

### ISSUE THREAD

**Issue by mcarans** [konstantinstadler/country_converter#35]
https://unterm.un.org/UNTERM/Display/Record/UNHQ/NA/01b637e1-1497-4825-b73d-e0114a7f4d22

**Comment by konstantinstadler** [comment]
Thanks a lot for that. I will update coco when I am back from paternity leave (September).

**Comment by konstantinstadler** [comment]
Resolved in 10972c3 (develop) - will be on master in the next version (0.6.6)
