### ISSUE TITLE
Congo Dem. Rep.

### ISSUE THREAD

**Issue by louisguitton** [konstantinstadler/country_converter#38]
Great job on this library. Easy to use and doing what it says on the can.
I had an issue with Congo vs DRC though. See the reproducible snippet below: 
```python
import country_converter as coco
some_names = ['Congo, Dem. Rep.',  'Congo, Rep.']
standard_names = coco.convert(names=some_names, to='name_short')
In [96]: standard_names
Out[96]: [['Congo Republic', 'DR Congo'], 'Congo Republic']
```
expected output is `['DR Congo', 'Congo Republic']`

**Comment by louisguitton** [comment]
going to have a look at `CONTRIBUTING.rst` and see if I can fix it

**Comment by louisguitton** [comment]
🚀

**Comment by konstantinstadler** [comment]
Yeah, sorry for the delay (exactly 1 year I see) - that somehow slipped through...

**Comment by louisguitton** [comment]
aha I hadn't seen it was exactly one year. Time flies. No worries, thanks for your work. I never took the time to contribute actually 😞

**Comment by konstantinstadler** [comment]
no worries. The whole congo stuff is probably the hardest one to get started with regular expressions...
