### ISSUE TITLE
multiple matching

### ISSUE THREAD

**Issue by eivindlb** [konstantinstadler/country_converter#4]
If country names are stated multiple times, multiple country codes show.

e.g. China (P.R. of China and Hong Kong, China) becomes '[''CHN'', ''HKG'']' in ISO3 codes

**Comment by konstantinstadler** [comment]
Thats tricky - the names state that it is China and Hong Kong - wouldnt you expect both ISO3 codes?

**Comment by eivindlb** [comment]
Good point, probably best to leave it as is then. Or could a warning message of some sort be an alternative?

**Comment by konstantinstadler** [comment]
Ok, I close it than
