### ISSUE TITLE
Coerce inputs to convert to list

### ISSUE THREAD

**Issue by lagph** [konstantinstadler/country_converter#54]
Hi, thanks for the library.

I got bitten by unexpected behaviour upon passing a pandas series to `convert`. I would have expected the code either to raise a `TypeError` or to handle the input correctly. Instead, the series gets converted to a _single_ string, which is matched against the country regexes. In many cases this actually gives the correct result in the end (although with `Warning: More than one regular expression match for [list of all countries in series]` being printed a million times). In a few cases, the formatting of the series string somehow prevents a match, and so a country or two are not included in the result.

These lines are the root of the problem:
```python
names = list(names) if (
   isinstance(names, tuple) or
    isinstance(names, set)) else names

names = names if isinstance(names, list) else [names]

names = [str(n) for n in names]
```

If names is a pandas series, after these lines `names` will be a one-element list containing a single string representing the entire series (the result of calling `str` on the series).
The same thing will happen if you input a numpy array, or in fact anything which implements `__repr__`.

I suggest changing the code so it tries to coerce the input to a list, and raises a `TypeError` upon failure. For instance we could change the above lines to this:
```python
if not isinstance(names, str):
    try:
        names = list(names)
    except TypeError as e:
        raise TypeError("names must be coercible to list") from e
    names = [str(n) for n in names]
else:
    names = [names]
```
Happy to make a PR if you agree.

Thanks again for the library, saved me tonnes of work.

**Comment by konstantinstadler** [comment]
Great suggestion! If you want, go for a pr, otherwise I will implement in the next weeks (probably).
