### ISSUE TITLE
Does not work for "uk" and short name issue for Macau

### ISSUE THREAD

**Issue by suvinks** [konstantinstadler/country_converter#55]
**Issue #1** 

cc.convert(names='UK',to='name_short')

gives you the following result

**WARNING:root:UK not found in ISO2
'not found'**

the code looks only for ISO2 for 2 letter input, even though the regex check would have captured this correctly

**Issue #2**
cc.convert(names='macau',to='name_short') gives **macao**

Ideal name is https://en.wikipedia.org/wiki/Macau
Macau also works with another python package "CountryInfo"

**Comment by konstantinstadler** [comment]
Hi, 
Thanks for the feedback.
The name of Macao|u is changed now.
For the UK stuff  - this will stay that way, please pass `src='regex'` (most of the commonly used 2 letters acronyms are in the regex).

see also
https://github.com/konstantinstadler/country_converter/issues/64#issuecomment-677652734
