### ISSUE TITLE
Country: Yugoslavia is not the the .tsv file

### ISSUE THREAD

**Issue by muhammadumerjaved44** [konstantinstadler/country_converter#57]
WARNING:root: Yugoslavia not found in regex

**Comment by konstantinstadler** [comment]
Hi
Yugoslavia dissolved 1992 - so far I did not have the need to include it.

You can add new countries in the tsv file ( https://github.com/konstantinstadler/country_converter/blob/master/CONTRIBUTING.rst ) or also combine the given list with a custom one - see "Handling missing data" here: https://github.com/konstantinstadler/country_converter/blob/master/doc/country_converter_examples.ipynb
