### ISSUE TITLE
correcting names within a dataframe

### ISSUE THREAD

**Issue by thap2331** [konstantinstadler/country_converter#58]
Thank you for this package to @konstantinstadler 
I have a quick question to whoever can answer and am wondering if we can do this using this package? I have a dataframe (in pandas format) and have a list of countries on one column. There could be multiple duplicates. Example:
df = pd.DataFrame({"Country":["Afghanistan ","Afghanistan ", " Afghanistan", "Åland Island", "Åland Islan"], "Values":[23,45,46,787,875]})

As you can see, some of them have trailing whitespace, some names are not complete, and etc. I know we can fix this issue using regex. But I am wondering if you have already done this for us? Let's assume I want my county name fixed according to UN member.  I want a extra column which has fixed all errors i.e. col = Country, Values, Country_NameFixed
Goal : I want to input a df and want a pd.DF at the end.

**Comment by konstantinstadler** [comment]
Hi,
Happy to see that you find it useful! 
Not sure what you mean "fixed according to UN member" but this might point you in the right direction

```
In [1]: import country_converter                                                                                                                      

In [2]: import pandas as pd                                                                                                                           

In [3]: df = pd.DataFrame({"Country":["Afghanistan ","Afghanistan ", " Afghanistan", "Åland Island", "Åland Islan"], "Values":[23,45,46,787,875]})    

In [4]: df.loc[:, "Country_NameFixed"] = country_converter.convert(df.Country.tolist(), src="regex", to="name_short")                                 

In [5]: df                                                                                                                                            
Out[5]: 
        Country  Values Country_NameFixed
0  Afghanistan       23       Afghanistan
1  Afghanistan       45       Afghanistan
2   Afghanistan      46       Afghanistan
3  Åland Island     787     Aland Islands
4   Åland Islan     875     Aland Islands

```
