### ISSUE TITLE
"Republic of Ireland"

### ISSUE THREAD

**Issue by mherreshoff** [konstantinstadler/country_converter#60]
First of all thanks for building this.  I've been reconciling some geographic data by hand the tedious way so far and this looks like it's going to be a huge time saver.  The one country string from my data source that country_converter didn't recognize was "Republic of Ireland", which is one of the official names of Ireland. See: [ https://en.wikipedia.org/wiki/Republic_of_Ireland ]. For myself, I'm just going to put in an if statement to catch it, but I thought you might want to know.

Thanks again!

**Comment by AlexandrG27** [comment]
Same issue

**Comment by AlexandrG27** [comment]
It also doesn't work if i just print 'Ireland'

**Comment by konstantinstadler** [comment]
Should be fixed now, see 
https://github.com/konstantinstadler/country_converter/issues/64#issuecomment-677652734

Let me know if there are still problems
