### ISSUE TITLE
Can coco.match warnings be suppressed?

### ISSUE THREAD

**Issue by rasheed72** [konstantinstadler/country_converter#63]
I'm not sure if this is best done outside or inside of the match function, but usually when I run the function I'm aware that some matches won't be found and will look for and deal with multiple matches. Meanwhile the long list of warnings pushes useful information further away in my terminal. Can the warnings be turned off or piped somewhere out of the way?

**Comment by konstantinstadler** [comment]
See #59

**Comment by rasheed72** [comment]
Thank you. I didn't realize that.
