### ISSUE TITLE
PyPi release 

### ISSUE THREAD

**Issue by sbrugman** [konstantinstadler/country_converter#71]
@konstantinstadler Could you please make another PyPi release? 
(If it takes much effort, consider automating parts of the release steps via [`twine`/Github Actions](https://github.com/pandas-profiling/pandas-profiling/blob/master/.github/workflows/pypi.yml))

**Comment by konstantinstadler** [comment]
Still working on some new classifications, comes next week

**Comment by konstantinstadler** [comment]
0.7.0 is on pypi now, conda will follow soon

**Comment by sbrugman** [comment]
Great, thank you.
