### ISSUE TITLE
List of options to convert name to

### ISSUE THREAD

**Issue by rlonka** [konstantinstadler/country_converter#75]
Hi,
I would like to have list of option I can use to convert country names to. Like convert_options = ['iso2', 'iso3', 'short_name', etc...]
ATM there is valid_class attribute but this will return all options together with country groups.
I can try to implement it, but I am not sure what is starting point. Where is such a information. 

regards,
Radek

**Comment by ChrisjanWust** [comment]
Hi @rlonka 

Here's an example of how to implement the functionality you require as a function:

```python
import country_converter as coco

cc = coco.CountryConverter()

def get_full_country(country, fields):
    iso2_code = cc.convert(country, to="ISO2")
    return cc.data.set_index("ISO2", drop=False).loc[iso2_code][fields].to_dict()

print(get_full_country("ZA", fields=["ISO2", "name_short", "continent"]))
# {'ISO2': 'ZA', 'name_short': 'South Africa', 'continent': 'Africa'}
```

That said, I'm not 100% sure whether it's worth it to add the interface to the library.
