### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rgieseke** [konstantinstadler/country_converter#8]
As part of my review (https://github.com/openjournals/joss-reviews/issues/332) a question on licensing:

More than anything, the choice of license is also cultural (https://twitter.com/hadleywickham/status/873554179792355328) and it seems that permissive licenses are more popular for Python projects. Given that `country_converter` is "infrastructure" and not a scientific model, maybe it could make sense to release under BSD or MIT? This could improve its adoption, I have noted that some Python projects are reluctant to include GPL-ed code. There are of course good reasons to choose GPL and I have myself used it in scientific projects.

If you chose GPL because it in part builds on https://github.com/vincentarelbundock/countrycode, then maybe its authors should be mentioned in the [LICENSE](https://github.com/konstantinstadler/country_converter/blob/master/LICENSE) file?

**Comment by konstantinstadler** [comment]
I agree, that licensing is a controversial issue. 
I very much agree with the GNU philosophy (https://www.gnu.org/licenses/quick-guide-gplv3.en.html) and would therefore rather keep the current licence.

**Comment by rgieseke** [comment]
That's great, just wanted to make sure! 
The `setup.py file` lists "GPLv3 or later" in the classifier, I believe the "license" field is thus unnecessary: 

> The license field is a text indicating the license covering the package where the license is not a selection from the “License” Trove classifiers. See the Classifier field.

https://docs.python.org/3/distutils/setupscript.html#additional-meta-data

Maybe the "or later" should be stated clearly also in other places?

**Comment by konstantinstadler** [comment]
Ok, thanks for pointing that out. I removed the licence field and changed to just gpl3 - dont know exactly how I would handle "or later"
