### ISSUE TITLE
This is the slowest library I have ever used for anything

### ISSUE THREAD

**Issue by rjurney** [konstantinstadler/country_converter#83]
I am running country names through this library, which from the debug output seems to use regex matching, to get the official and 2-letter codes for countries. This is taking half a second each!

```python
record["nation"] = coco.convert(names=record["nation"], to="name_official")
record["nation_code"] = coco.convert(names=record["nation"], to="ISO2")
```

Can you explain why this takes so long and how the speed might be improved? This library works great, but at this rate of speed it can't be used on datasets of any size without paying a large amount of currency to process the data just to standardize countries.

**Comment by konstantinstadler** [comment]
perhaps have a look at the readme

**Comment by rjurney** [comment]
@konstantinstadler I may be mistaken, in which case this will not be the first dumb thing I've said but... I read it. And I don't understand how it addresses my speed concern. Your library is awesome. How can I make it go faster?

**Comment by konstantinstadler** [comment]
Hi, perhaps you already do this - I was referring to
"In case of multiple conversion, better performance can be achieved by instantiating a single CountryConverter object for all conversions: ..."

In case you are working with pandas dataframe, you could also experiment with the apply function of pandas (never used coco in that way, but should work principally).

**Comment by rjurney** [comment]
> Hi, perhaps you already do this - I was referring to
> 
> "In case of multiple conversion, better performance can be achieved by instantiating a single CountryConverter object for all conversions: ..."
> 
> 
> 
> In case you are working with pandas dataframe, you could also experiment with the apply function of pandas (never used coco in that way, but should work principally).

Thank you. I probably should have figured this out. I am using PySpark and am not sure if I retained the object or not. I'll try this, thanks!

**Comment by rjurney** [comment]
I am still struggling with this in PySpark.
