### ISSUE TITLE
convert() regex suggestions

### ISSUE THREAD

**Issue by knyipab** [konstantinstadler/country_converter#84]
HKSAR => Hong Kong
N. Korea => North Korea

**Comment by knyipab** [comment]
Macau SAR (China) => Macau

**Comment by knyipab** [comment]
Macau SAR, China => Macau

**Comment by knyipab** [comment]
It has something to do with the regex of China
`^(?!repub)(?!taiwan)(?!hong.*kong)(?!macao).*china(?!.*hong.*kong)(?!.*macao)|^PRC$`
Maca**u**, potentially
`^(?!repub)(?!taiwan)(?!hong.*kong)(?!macao)(?!macau).*china(?!.*hong.*kong)(?!.*macao)|^PRC$`

**Comment by konstantinstadler** [comment]
Thanks a lot for these - fixed on master and will be on pypi soon
