### ISSUE TITLE
FutureWarning: The default value of regex will change from True to False in a future version.

### ISSUE THREAD

**Issue by ahgraber** [konstantinstadler/country_converter#85]
When using with python=3.7.10 and pandas=1.2.3, I receive the following warning with country_converter:

... 
`/miniconda3/envs/clv/lib/python3.7/site-packages/country_converter/country_converter.py:578: FutureWarning: The default value of regex will change from True to False in a future version.
  _match_col = self.data[src_format].astype(str).str.replace("\\..*", "")`
...

I wonder if explicitly setting str.replace() regex flag would solve this (for pandas > 0.23); recommend doing so in all instances of pd.str.replace(): `pd.str.replace()` 

From pandas source code, here is what is generating the warning:
```
        if regex is None:
            if isinstance(pat, str) and any(c in pat for c in ".+*|^$?[](){}\\"):
                # warn only in cases where regex behavior would differ from literal
                msg = (
                    "The default value of regex will change from True to False "
                    "in a future version."
                )
                if len(pat) == 1:
                    msg += (
                        " In addition, single character regular expressions will"
                        "*not* be treated as literal strings when regex=True."
                    )
                warnings.warn(msg, FutureWarning, stacklevel=3)
            regex = True
        result = self._data.array._str_replace(
            pat, repl, n=n, case=case, flags=flags, regex=regex
        )
```

**Comment by konstantinstadler** [comment]
thanks, will be done
