### ISSUE TITLE
False matches

### ISSUE THREAD

**Issue by BenPortner** [konstantinstadler/country_converter#86]
Dear @konstantinstadler 

first off, thanks for this great tool! It is such a relieve to have a working solution to match country names from different sources! Pure gold!

Today, I downloaded data from the [Global Burden of Disease website](http://ghdx.healthdata.org/gbd-results-tool) and tried to assign ISO codes using your tool. Most of the matches were spot on. However, the converter seemed to struggle with a few cities / regions, which have very similar names to countries. Here is the complete list of false matches:

name | false match
-- | --
Southern Sub-Saharan Africa | South Africa
Mexico City | Mexico
New Jersey | Jersey
West Papua (province of Indonesia) | Papua New Guinea
Papua (province of Indonesia) | Papua New Guinea
Sweden except Stockholm | Sweden
New Mexico | Mexico
Norfolk (county in England) | Norfolk Island

I don't know if it is feasible to remove these without breaking anything. I guess a certain amount of false matches is natural. The only way I can think of, is to include them as exceptions?

All the best.
Ben

**Comment by konstantinstadler** [comment]
Thanks for reporting these. My plan is, to make country converter to just run with any of the public db. So this is really helpful and I will fix that. I think most of these should just be no match, the only exception might be "Sweden except Stockholm" - this should probably match to Sweden? What do you think?

**Comment by BenPortner** [comment]
Hi @konstantinstadler,
I agree that most of these should not be matches. For my application, `Sweden except Stockholm` should not match to `Sweden` either, since GBD has an extra entry for `Sweden` as a whole. I can see that there might be applications where they should match, though. Your choice :)

I just found another mismatch, and this is a tough one: `Georgia` (US state) matches to `Georgia` (country). I guess this one is impossible to solve without context?

**Comment by konstantinstadler** [comment]
Good point. You encountered the first case with "Sweden except Stockholm" - and if this database also includes Sweden I will exclude "Sweden except Stockholm" as a match. 

for Georgia: So there is just the name, without >(US state)< - that will be difficult.

**Comment by BenPortner** [comment]
> that will be difficult.

I agree 😅 

To avoid potential confusions: the brackets in my first table above are not part of the original names. I added them for clarification. I.e. GBD contains `West Papua`, without `(province of Indonesia)` and `Norfolk` without `(county in England)` and so on.

**Comment by konstantinstadler** [comment]
Ah - ok, so I start again (was matching against the brackets...=

**Comment by BenPortner** [comment]
My bad! I should have been more clear. Sorry for the double work.

Concerning Georgia: 
Possibly, one could discriminate both Georgias by using their IDs (Georgia in USA: 533, Georgia country: 35). This could be generalized by implementing two optional arguments in the converter function: 
- on to pass the name of an ID column, e.g. `location_id`
- a second one to pass the name of the scheme, e.g. `GBD`

The IDs could then be used to differentiate in cases where multiple locations have the same name. If the user does not provide this info, the default mapping will be used and false matches might occur. Of course, this requires implementing and maintaining the different ID schemes, e.g. UN, GBD, ISO, which might be too much work. What do you think?

**Comment by konstantinstadler** [comment]
not sure what you mean. If you have an id, you could just use the ids we already have in the country converter (I would alway recommend to use the UNnumeric, ISO3, or whatever instead of relying on regex). If there is another id scheme which is not implemented yet, we could also think about that.
Anyway, the cases from the first message should be covered now - currently only on git/master, I have some other issues to solve before making a new version

**Comment by BenPortner** [comment]
Thanks for fixing this so fast :)

You are right, if I have codes for all the locations, then it's more accurate to use these for matching. As far as I can see, the GBD scheme is not implemented yet. Would it be possible introduce it? The codes can be found (together with other files) in their [codebook.](http://ghdx.healthdata.org/sites/default/files/ihme_query_tool/IHME_GBD_2019_CODEBOOK.zip)

**Comment by konstantinstadler** [comment]
Thanks. I will have a look after easter. Or, if you want, you can also have a try. Basically you just need to add another column to the country tsv file and add the codes per country

**Comment by konstantinstadler** [comment]
added in 0.7.3, thanks for the suggestion

**Comment by BenPortner** [comment]
@konstantinstadler Thank you so much! Sorry that I didn't help more. Keep up the amazing work!
