### ISSUE TITLE
UK not recognised

### ISSUE THREAD

**Issue by knyipab** [konstantinstadler/country_converter#92]
"UK" is treated as an ISO2 and not recognized with `WARNING:country_converter.country_converter:uk not found in ISO2`. I highly suspect this might be due to the program logic given that given that your package's regex `.*(united.?kingdom|britain|^u\.?k\.?$|gb)` seems to be work on "UK". 

Fyi, `re.match('.*(united.?kingdom|britain|^u\.?k\.?$|gb)', 'UK', re.IGNORECASE)` does work.

Please consider to change the program logic to allow "UK" to be regcognized. Thanks!

**Comment by konstantinstadler** [comment]
Not sure what you think the expected behaviour should be. The official iso2 is 'GB' , country converter captures uk through regex:
https://en.m.wikipedia.org/wiki/ISO_3166-2:GB

**Comment by konstantinstadler** [comment]
See also #55

**Comment by knyipab** [comment]
Thanks for your explanation and link to #55. Just in the case that "UK" is not in ISO2 list, wouldn't it be good to use regex when it is not in ISO (and `src=` is not specified)? 
It is just a bit weird that a `coco.convert(['UK', 'Ireland'])` won't work while `coco.convert(['U.K.', 'Ireland'])` works. And there are some database does use "UK" in its country field. Okay, this is more a feature request now, givent the existence of #55.

**Comment by konstantinstadler** [comment]
Yeah. Coco tries to guess the classification based on number of letters in the string (if src= is not given). This fails for some common abbreviations. I will think about that in August

**Comment by davidjb99** [comment]
I agree UK should be matched with GB, it's a very common abbreviation
