### ISSUE TITLE
issue with some countries

### ISSUE THREAD

**Issue by vlasvlasvlas** [konstantinstadler/country_converter#94]
Hi! i have some old iso3 issue with this countries, could this be added to custom data?

#Palestine: ISO 3166-1 alpha-3 on column 'CODE' corresponds to  West Bank & Gaza (WBG instead of PSE)
#Kosovo: ISO 3166-1 alpha-3 on column 'CODE' = KSV in source instead of corresponding XKX
#Congo, Dem. Rep.: ISO 3166-1 alpha-3 on column 'CODE' = ZAR in source instead of corresponding COD
#Romania: ISO 3166-1 alpha-3 on column 'CODE' = ROM in source instead of corresponding ROU
#New Caledonia is not reported in source

thanks!

**Comment by konstantinstadler** [comment]
Hi,
you can pass a custom data file with these values.

see around Out[15] here
